### ISSUE TITLE
(New Switches)

### ISSUE THREAD

**Issue by imjustakeyboredperson** [tplai/kbsim#25]
You should add some more switches and have lube for them (i hope u know what i mean by lube *NOT THAT LUBE*

**Comment by tplai** [comment]
I was thinking about adding BobaU4Ts and some gateron switches to the main site, but I'm going to put switch requests on hold for now until the desktop version is released. Right now, the priority is to release desktop so everyone can use kbsim outside of the website. Then I'll go back to switch requests.

**Comment by imjustakeyboredperson** [comment]
Ok man Keep up the work :)

**Comment by tplai** [comment]
Closing this issue for now.
